/** Short texts (hover / aria-label) and long sections (help dialog). */

export const TIP = {
  connectionOk: "Connected to the relay master metrics endpoint.",
  connectionErr: "Failed to read metrics — relay offline or wrong URL.",
  range1m: "Charts: last 1 minute of server history.",
  range10m: "Charts: last 10 minutes of server history.",
  range1h: "Charts: last 1 hour of server history.",
  helpBtn: "Open detailed metrics and master flow guide.",

  producers: "Producer clients on TCP control :9750 — PRDY/HBRP.",
  consumers: "Consumer clients on the same :9750 (REG!/CRDY) + BATC data :9760+.",
  producerBacklog: "Msgs on producers (pending + ring) via HBRP heartbeat.",
  producerPending: "Queue before the accumulator (direct publish_batch).",
  producerRing: "Ready batches waiting for ASSIGN.",
  consumerInflight: "Consumers with a batch in flight (await BATC or processing).",
  consumersAwaitBatch: "Consumers with ASGN — BATC in transit, DELV pending on master.",
  consumerCapacityAvg:
    "Average μ/λ × 100 per consumer (>100% = average headroom; <100% = average lag). Global pool in tooltip.",
  transferRate: "Msgs transferred/s — same sample as Transfer rates chart (2s history).",
  avgMsgSize:
    "Average size per message: transfer_bytes_total ÷ transfers_total (BATC payload per item).",
  bytesRate: "BATC rate in Mbps or Gbps (bytes/s × 8, SI).",
  batchesRate: "BATC batches/s — same sample as Transfer rates chart (2s history).",
  avgBatchSize:
    "Average BATC batch size: bytes/s ÷ batches/s in the interval (payload per RTT).",
  deliveryErrorsRate: "BATC failures/s (FAIL + local requeue).",
  deliveryErrors: "Total FAIL since boot + requeued msgs.",
  drops: "Drops on producer rings in the chart interval.",
  dropsRate: "Drop rate/s on rings (HBRP) — right axis on backlog chart.",
  historyPts: "Points in the history buffer (~2s).",

  panelBacklog: "Backlog on producers, inflight on consumers, and drop history.",
  panelRates: "BATC/TCP transfer rates.",
  panelMatch: "Matchmaker state — PRDY and CRDY pools.",
  chartBacklog: "Backlog time series chart.",
  chartRates: "Transfer/s and bitrate (Mbps/Gbps) time series chart.",
  chartMatch: "Matching pool time series chart.",

  producersReady: "Producers in PRDY pool waiting for a consumer.",
  producersBusy: "Producers in ASSIGN/BATC.",
  consumersWaiting: "Consumers in matcher queue (CRDY ack, ASGN pending).",

  flowMaster: "Master orchestrates PRDY↔CRDY; payload goes over BATC TCP P2P.",
  flowProducers: "Producers — local ring + accumulator.",
  flowConsumers: "Consumers — REG!, CRDY, receive BATC.",
  flowDownstream: "Application processing after the consumer receives a batch.",
  flowArrowControl: "TCP control :9750 — PRDY when ring has batch; HBRP ~2s.",
  flowArrowBatc: "Producer sends BATC to consumer data_addr after ASGN.",
  flowArrowConsumer: "Consumer TCP :9750 — REG!, CRDY, ACK.",
  flowGraph:
    "Persistent dashed purple line = busy producer paired with consumer awaiting BATC. Tick assign/deliver/fail animates on top.",

  colMenu: "Choose visible table columns (saved in browser).",
  producersTable: "Backlog per producer — HBRP heartbeat data.",
  consumersTable: "State per consumer — updates every poll (~2s).",
} as const;

export const COLUMN_TIPS: Record<string, string> = {
  id: "Internal TCP session ID on the relay.",
  consumer_tag: "Tag sent in CRDY or generated by the relay.",
  addr: "TCP connection IP:port.",
  data_addr: "Data-plane TCP address where producer sends BATC.",
  state:
    "await CRDY — between batches; match queue — CRDY in queue; await BATC — waiting for batch; processing; BATC failed.",
  capacity:
    "μ/λ × 100: observed vs fair share. >100% = headroom (can take more load); <100% = behind.",
  ready_cycle_ms: "EMA ms between delivered batch and next CRDY.",
  max_batch_requested: "max_items from the last CRDY.",
  unacked: "Items from the last batch still being processed.",
  batches_per_sec: "Batch rate/s — sample between relay polls.",
  bitrate: "Byte rate/s → Mbps/Gbps — sample between relay polls.",
  last_batch_items: "Items in the last successful batch.",
  last_batch_bytes: "Bytes in the last successful batch.",
  connected_secs: "Time since TCP connect.",
};

export const PRODUCER_COLUMN_TIPS: Record<string, string> = {
  id: "Internal TCP session ID on the master.",
  addr: "Producer IP:port.",
  state: "idle — connected; ready — PRDY sent; busy — ASSIGN/BATC in progress.",
  pending_messages: "Msgs in queue before accumulator (publish_batch).",
  ring_messages: "Ready batches waiting for ASSIGN.",
  backlog_messages: "pending + ring (msgs waiting for transfer).",
  pending_bytes: "Bytes in pending queue.",
  ring_bytes: "Bytes in dispatch ring.",
  backlog_bytes: "Total bytes in local backlog.",
  drops_per_sec: "Msg drop rate/s (full ring) — HBRP delta on master.",
  batches_per_sec: "Successful BATC batch (DELV) rate/s — master window.",
  msgs_per_sec: "Msgs delivered via successful BATC/s — master window.",
  errors_per_sec: "BATC failure (FAIL) rate/s — master window.",
  connected_secs: "Time since TCP connect on :9750.",
};

export interface HelpSection {
  title: string;
  body: string;
}

export const HELP_SECTIONS: HelpSection[] = [
  {
    title: "Overview (master)",
    body:
      "Master mode: no central queue on the relay. Producer accumulates batches locally, " +
      "signals PRDY; consumer sends CRDY; master matches and sends ASGN to producer; " +
      "producer sends BATC directly to the consumer. Metrics reflect BATC transfers and producer backlog (HBRP).",
  },
  {
    title: "Summary bar",
    body:
      "Producers ready/busy — matching pool.\n\n" +
      "Consumers queue/await — matcher queue vs ASGN done awaiting BATC.\n\n" +
      "Producer backlog — sum of pending+ring reported via HBRP.\n\n" +
      "Transfer — msg/s and batch/s measured on master (DELV).\n\n" +
      "Delivery errors — FAIL + local requeue on producer.",
  },
  {
    title: "Producer backlog",
    body:
      "Pending — queue before accumulator (publish_batch).\n\n" +
      "Ring — batches ready for ASSIGN.\n\n" +
      "Consumer inflight — batches already matched, waiting or in processing.\n\n" +
      "Drops — msg drop rate/s (full ring), right axis.",
  },
  {
    title: "Transfer rates (BATC)",
    body:
      "Transfer/s — messages confirmed via DELV.\n\n" +
      "Bytes/s — BATC TCP volume.\n\n" +
      "Batches/s — complete BATC deliveries (+ paired bitrate in legend).\n\n" +
      "Delivery errors/s — FAIL (timeout, connect, etc.) with requeue on local ring.",
  },
  {
    title: "Producers table",
    body:
      "HBRP heartbeat every ~2s: pending/ring msgs+bytes, drops. " +
      "Requires producer rebuild after protocol upgrade.",
  },
  {
    title: "Protocol (reference)",
    body:
      "Producer→master: PRDY (ring has batch), HBRP (backlog), DELV/FAIL (BATC result).\n\n" +
      "Consumer→master: REG! (data_addr), CRDY (max_items, tag).\n\n" +
      "Master→producer: ASGN (max_items, tag, data_addr).\n\n" +
      "Data plane: BATC (producer→consumer). Successful delivery = TCP flush.",
  },
];
